# src: ./configs/.markdownlint-cli2.yaml
# @(#) : markdown linter execute config
#
# Copyright (c) 2025- atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

## Files
globs:
  - "**/*.md"

## Ignores
# ignore gitignore
gitignore: true
# ignore files globs
ignores:
  - ".serena/**"
  - ".tools/**"

## ruleset
config:
  extends: .markdownlint.yaml
